namespace Curiosity.FrontEnd.Recipes.Recipes._05_NodeRenderer
{
    /// <summary>
    /// Compile-time constants for the schema the INodeRenderer recipe registers and renders.
    /// Mirrors the pattern auto-generated by the workspace template into <c>Schema.cs</c>.
    /// </summary>
    public static class RecipeN
    {
        public sealed class RecipeBook
        {
            public const string Type   = nameof(RecipeBook);
            public const string Title  = nameof(Title);
            public const string Author = nameof(Author);
            public const string Year   = nameof(Year);
            public const string Genre  = nameof(Genre);
            public const string ISBN   = nameof(ISBN);
        }
    }
}
