<Project Sdk="h5.Target/26.3.64912">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>7.2</LangVersion> <!-- H5 compiler supports C# 7.2 -->
    <NoWarn>CS1998;CA2007</NoWarn>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <DefineConstants>H5</DefineConstants>
    <RootNamespace>FrontEnd.Recipes</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="h5" Version="26.2.64514" />
    <PackageReference Include="h5.core" Version="26.4.580" />
    <PackageReference Include="h5.Newtonsoft.Json" Version="26.3.65451" />
    <PackageReference Include="Plotly.H5" Version="2025.9.61626" />
    <PackageReference Include="Tesserae" Version="2026.5.66415" />
    <PackageReference Include="Mosaik.FrontEnd.API" Version="26.5.840" />
    <PackageReference Include="Mosaik.FrontEnd.Core" Version="26.5.840" />
    <PackageReference Include="Mosaik.FrontEnd.Admin" Version="26.5.840" />
    <PackageReference Include="Mosaik.FrontEnd" Version="26.5.840" />
  </ItemGroup>
</Project>
